apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonar.name" . }}-secret
  labels:
    {{- include "sonar.labels" . | nindent 4 }}
type: Opaque
# In this case I'm putting credential as plain text from values file, for a real scenario, values should go from key vault (for example Azure KeyVault)
# Since it is a homework, and made for local development, I'm not using any vault for storing these values
stringData:
  SONAR_JDBC_USERNAME: {{ .Values.database.user }}
  SONAR_JDBC_PASSWORD: {{ .Values.database.password }}