apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sonar.name" . }}
  labels:
    {{- include "sonar.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "sonar.name" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        {{- include "sonar.labels" . | nindent 8 }}
        app: sonarqube
    spec:
      automountServiceAccountToken: false
      containers:
        - name: sonarqube
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SONAR_SEARCH_JAVAOPTS
              value: "-Xms256m -Xmx256m"
            - name: SONAR_WEB_JAVAOPTS
              value: "-Xms128m -Xmx256m"
            - name: SONAR_CE_JAVAOPTS
              value: "-Xms128m -Xmx256m"
            - name: SONAR_JDBC_URL
              value: jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
            - name: SONAR_JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonar.name" . }}-secret
                  key: SONAR_JDBC_USERNAME
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonar.name" . }}-secret
                  key: SONAR_JDBC_PASSWORD
          ports:
            - name: http
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 10
          volumeMounts:
            - name: {{ include "sonar.name" . }}-data
              mountPath: /opt/sonarqube/data
  volumeClaimTemplates:
    - metadata:
        name: {{ include "sonar.name" . }}-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}